### ISSUE TITLE
[Issue] Mac 上使用预览功能，选中文本不能调出 ClickNow

### ISSUE THREAD

**Issue by yangwenmai** [laike9m/Xylect#12]

**Comment by laike9m** [comment]
Hi, 预览指的是这个 app 吗？方便的话可以截个图
<img width="564" alt="image" src="https://github.com/user-attachments/assets/4bcab67a-fc16-4c9c-91fc-c1ca28ebab9a">

**Comment by laike9m** [comment]
如需后续讨论，请移步 github.com/laike9m/Clicknow 或 https://www.reddit.com/r/ClicknowAI/
