### ISSUE TITLE
可以添加google日历但是添加不到apple日历

### ISSUE THREAD

**Issue by zg9uagfv** [laike9m/Xylect#4]
系统信息：
MacBook Pro m1 max
OS version:15.0.1

软件版本：clicknow1.9.4

日历的权限也打开了，
![image](https://github.com/user-attachments/assets/8be4da46-f9f6-4ed6-ae89-acf145ebd9f2)

事件可以添加google日历但是添加不到apple日历

**Comment by laike9m** [comment]
Telegram 回复你了
