### ISSUE TITLE
使用双击不显示悬浮窗

### ISSUE THREAD

**Issue by GuyCui** [laike9m/Xylect#9]
更新最新版点击双击不弹窗

**Comment by laike9m** [comment]
设置了键盘快捷键双击就不会弹窗了

**Comment by laike9m** [comment]
<img width="552" alt="image" src="https://github.com/user-attachments/assets/7376dc9e-6849-4013-ad03-0c7d37995e1b">

**Comment by GuyCui** [comment]
谢谢 Dock图标可不可以设置隐藏 还有查询的单词或者句子能不能发音 不然还要使用bob进行发音

**Comment by laike9m** [comment]
> Dock图标可不可以设置隐藏
Clicknow 是没有 Dock 栏图标的，你指的是 status bar ？

> 还有查询的单词或者句子能不能发音
在计划内了

**Comment by GuyCui** [comment]
![image](https://github.com/user-attachments/assets/49e2f5c5-0a85-4550-9d02-32727ad12823)
就是zhe'g这个一直在显示 状态栏中已经显示了 这里就不要再显示了 怪占地方的

**Comment by laike9m** [comment]
收到。这是个 bug，正常是不会有的。您能重启一下看还有没有吗？

**Comment by GuyCui** [comment]
可能更新app版本出现的  重启电脑消失了 后面可以优化一下 其它没有什么问题了 有什么用户反馈群吗 在群里应该比这联系方便 谢谢

**Comment by laike9m** [comment]
官方用户论坛在这
https://www.reddit.com/r/ClicknowAI/s/Gvos6jzMch

急的话也可以直接 Telegram 找我
